version: "3.9"

services:
  media.harbor.bot:
    restart: always
    image: gsmelford/mediaharbor.bot:beta_1.0
    container_name: media.harbor.bot
    environment:
      - TBotOptions:Token=${MEDIA_HARBOR_BOT_TOKEN}
      - RedisOptions:Host=redis
      - RedisOptions:Password=${REDIS_PASSWORD}
      - RedisOptions:DefaultDatabase=1
      - RedisOptions:SyncTimeout=3000
      - KafkaOptions:BootstrapServers=kafka
    volumes:
      - /var/docker/mediaharbor/contents:/contents

networks:
  default:
    external:
      name: kafka_network