version: "3.9"

services:
  media.harbor.bot:
    restart: always
    image: gsmelford/mediaharbor.bot:beta_1.0
    container_name: media.harbor.bot
    environment:
      - TBotOptions:Token=$${{ secrets.MEDIA_HARBOR_BOT_TOKEN }}
      - TBotOptions:RedisOptions:Host=redis
      - TBotOptions:RedisOptions:Password=$${{ secrets.REDIS_PASSWORD }}
      - TBotOptions:RedisOptions:DefaultDatabase=1
      - TBotOptions:RedisOptions:SyncTimeout=3000
      - KafkaOptions:BootstrapServers=kafka