name: CI to Docker Hub

on:
  push:
    branches: [ main ]
  
jobs:
  Build:
    runs-on: windows-runner
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Login Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
  
    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: gsmelford/mediaharbor.bot:beta_1.0
        platforms: linux/amd64,linux/arm64
        build-args: |
            NUGET_USERNAME=${{ secrets.NUGET_USERNAME }}
            NUGET_PASSWORD=${{ secrets.NUGET_PASSWORD }}
  Deploy:
    runs-on: ryokutek-raspberrypi
    needs: Build
    steps:
    - name: MediaHarbor.Bot Down
      run: sudo docker compose down
    - name: MediaHarbor.Bot Update
      run: sudo docker compose pull
    - name: MediaHarbor.Bot Up
      run: sudo docker compose up -d
        
