name: MediaHarborBot
on: 
  push: 
    branches: [main]
jobs:
  nuget:
    runs-on: windows-runner
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
        docker build -t gsmelford/mediaharbor.bot:beta_1.0 .

    - name: Docker Login
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Push Docker Image
      run: docker push gsmelford/mediaharbor.bot:beta_1.0
