name: CI to Docker Hub

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    runs-on: ryokutek-raspberrypi
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up .env file
      run: |
          sed -i "s/MEDIA_HARBOR_BOT_TOKEN=/MEDIA_HARBOR_BOT_TOKEN=${{ secrets.MEDIA_HARBOR_BOT_TOKEN }}/g" .env
          sed -i "s/REDIS_PASSWORD=/REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}/g" .env

    - name: MediaHarbor.Bot Down
      run: sudo docker compose down
      continue-on-error: true
      
    - name: MediaHarbor.Bot Update
      run: sudo docker compose pull
    
    - name: MediaHarbor.Bot Up
      run: sudo docker compose up -d
